name: Go

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: docker/setup-buildx-action@v2.8.0

    - name: Docker Login
 
      uses: docker/login-action@v2.2.0
      with:
        username: danielafdc
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}